# Generated by Django 4.1.7 on 2023-05-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=200, verbose_name='Название')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('type', models.CharField(max_length=100, verbose_name='Тип мероприятия')),
                ('image', models.ImageField(blank=True, upload_to='events', verbose_name='Фото')),
                ('time', models.DateTimeField(verbose_name='Дата и время')),
                ('description', models.TextField()),
            ],
        ),
    ]
