# Generated by Django 4.1.7 on 2023-05-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_description_eventvisitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/events/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип мероприятия'),
        ),
    ]
