# Generated by Django 4.1.7 on 2023-05-21 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userprofile_image'),
        ('events', '0003_rename_tittle_event_title_alter_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
    ]
