# Generated by Django 4.1.7 on 2023-05-01 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_user'),
        ('shop', '0002_product_productcategory_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile', verbose_name='Продавец'),
        ),
    ]
