# Generated by Django 4.1.7 on 2023-05-07 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
